-- 权限表
CREATE TABLE permission (
  pid INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL DEFAULT '',
  url VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY(pid)
)ENGINE = innorDB DEFAULT CHARSET = utf8;
