#---------------------------------
#    ˝æ›ø‚≈‰÷√                     ||
#=================================
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8
    data-username: root
    data-password: root


